### ISSUE TITLE
Question to sergey part, 640 or 1024 size?

### ISSUE THREAD

**Issue by RedMoon32** [ZFTurbo/2nd-place-solution-for-VinBigData-Chest-X-ray-Abnormalities-Detection#5]
Question to Sergey Part, why he first resizes to 640 for inference, but then normalizes the resultant boxes like they were for 
1024*1024 pixels image?
```
pred_boxes, pred_scores, pred_labels = predict_for_files(weights, folder, imagenames, 640, is_TTA)
....
if len(cur_boxes) > 0:
    cur_boxes[:, [0, 2]] = (cur_boxes[:, [0, 2]] * image_width / 1024).astype(int)
    cur_boxes[:, [1, 3]] = (cur_boxes[:, [1, 3]] * image_height / 1024).astype(int)
```

**Comment by RedMoon32** [comment]
This seems like a mistake, I removed `* image_width / 1024`, `* image_height / 1024` and it worked for me
I can send a PR to fix it

**Comment by ZFTurbo** [comment]
Sergey said it's not bug. Initital images he worked with was 1024x1024. Neural net used 640px, so he just rescaled boxes back to initial image size.
